apiVersion: v1
kind: ServiceAccount
metadata:
  name: cron-user
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cron-user-binding
subjects:
  - kind: ServiceAccount
    name: cron-user
    namespace: default
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: deploy-cron-job
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: cron-user
          volumes:
            - name: deploy-script
              configMap:
                name: deploy-script
          containers:
          - name: cron-job-1
            image: bitnami/kubectl
            command: ["bash", "/usr/local/bin/deployScript.sh"]
            volumeMounts:
            - name: deploy-script
              mountPath: /usr/local/bin
          restartPolicy: OnFailure
