apiVersion: batch/v1

kind: CronJob

metadata:

  name: kubescheduler

spec:

  schedule: "* * * * *"

  jobTemplate:

    spec:

      template:

        spec:

          containers:
          - name: pipeline-scheduler
            image:  ghcr.io/ctron/kubectl:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - |
              kubectl get pods

          restartPolicy: OnFailure
